version: '3.8'

services:
  bi-service:
    build: .
    container_name: bi-service
    ports:
      - "3008:3008"
    environment:
      PORT: 3008
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""
      DB_NAME: portal_ecrt
      JWT_SECRET: bd1216e909de7d9443df38c00b79b8cefe90214bb976fd6ee0bd0563644d7d5735c34e960ab340bd38748a1205469b7d7ef6b76a32d44b699edaff81d606775b
      CRYPTO_SERVICE_URL: http://crypto-service:3009
    depends_on:
      - postgres
    networks:
      - bi-net

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: portal_ecrt
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - bi-net

networks:
  bi-net:
    driver: bridge